apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.secretName" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
type: Opaque
data:
  {{ include "clickhouse.secretUserKey" . }}: {{ .Values.externalClickhouse.user | b64enc }}
  {{ include "clickhouse.secretPasswordKey" . }}: {{ .Values.externalClickhouse.password | b64enc }}
