{{- if .Values.signozCollector.clusterRole.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "signozCollector.clusterRoleName" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  {{- with .Values.signozCollector.clusterRole.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules: {{ toYaml .Values.signozCollector.clusterRole.rules | nindent 2 -}}
{{- end }}
