{{- if .Values.signozCollector.clusterRole.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "signozCollector.clusterRoleBindingName" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "signozCollector.clusterRoleName" . }}
subjects:
  - name: {{ include "signozCollector.serviceAccountName" . }}
    kind: ServiceAccount
    namespace: {{ .Values.namespace | default .Release.Namespace }}
{{- end }}
