{{- if .Values.signozCollector.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "signozCollector.serviceAccountName" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "signozCollector.labels" . | nindent 4 }}
  {{- with .Values.signozCollector.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- include "signoz.imagePullSecrets" . }}
{{- end -}}
