apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otelCollector.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "otelCollector.labels" . | nindent 4 }}
data:
  otel-collector-config.yaml: |-
    {{- toYaml .Values.otelCollector.config | nindent 4 }}
